### PR TITLE
mongoose.createConnection should return a connection

### PR DESCRIPTION
**Pull request by omri-shaiko**
This PR return a connection from mongoose.createConnection function.

In order to do that i switched 3 functions (rimraf, mongod.start_server and portfinder.getPort) from being async to be sync using [deasync](https://github.com/abbr/deasync) library.

### CODE REVIEW

**Comment by gaggle** [comment]
+1, came here to report this exact issue (@ mockgoose 5.3.3)

**Comment by akoskm** [comment]
Any chance for this to be merged soon? Currently I'm dumping one of our development databases, restoring it in the CI environment and running integration tests on that one. :fire: 

However, because `createConnection` is preferred over `connect`

- http://stackoverflow.com/a/22838614/407466
- https://groups.google.com/d/msg/mongoose-orm/30Dopgbsd98/eeZq-V5OFD8J

I would rather not refactor my current code.

**Comment by winfinit** [comment]
I am not a fan of this approach, I think what would be worth doing is block and wait for mongod to start as soon as mockgoose is getting invoked, so before open call is issued from mongoose, which would allow us to handle createConnection and connect in a cleaner way.

**Comment by winfinit** [comment]
what I think needs to happen is modification of mongodb-prebuilt, change start function from using spawn to synchronous process creation, and add --fork argument to mongod, and since killer process is already in place, we won't even have to implement a stop hooks correctly, just fallback to killer.

**Comment by winfinit** [comment]
i've updated already mongodb-prebuilt to use spawnSync with --fork for mongod process, which gives us a good control over synchronous operations, now going to refactor a bit mockgoose, which would result in a nice, simplified structure I think, will keep you posted.

**Comment by akoskm** [comment]
Thanks a lot!

**Comment by kizinatural** [comment]
Hi Winfinit,

Is the fix for the sync connection already merged to master?
We would like to use it once it's ready.

Thanks!

**Comment by winfinit** [comment]
thank you for this PR, however code structure was changed to achieve this result, so strategies that were used in this request are no longer applied.

**Comment by scwood** [comment]
I think an issue I have might be related to this? I installed Mockgoose a few minutes ago, never seen this issue using it before.

When running my Mocha tests:

```
  1)  "before each" hook:
     Uncaught TypeError: Object #<Object> has no method 'spawnSync'
      at start (node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:70:26)
      at Object.start_server (node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:65:16)
      at node_modules/mockgoose/Mockgoose.js:144:42
      at next (node_modules/mockgoose/node_modules/rimraf/rimraf.js:74:7)
      at CB (node_modules/mockgoose/node_modules/rimraf/rimraf.js:110:9)
      at node_modules/mockgoose/node_modules/rimraf/rimraf.js:136:14
      at Object.oncomplete (fs.js:108:15)
```

Here is my beforeEach hook:

```javascript
beforeEach(function (done) {
  mockgoose(mongoose).then(function () {
    var options = {
      replset: { rs_name: config.mongo.replicaSet },
      user: config.mongo.username,
      pass: config.mongo.password,
      auth: { authdb: config.mongo.authenticationDatabase },
    };
    mongoose.connect(config.mogno.testDbUri, options);
  });
});
```

Node version is v0.10.42.

If this is unrelated, I'll be happy to make another issue.

**Comment by winfinit** [comment]
please create a new issue for this, ill need to mess with 0.10, i saw that few minutes ago too

**Pull request closed without merging**
