### PR TITLE
Added start_server_callback parameter to function mongodb.start_server

### PR DESCRIPTION
**Pull request by luigizuccarelli**
Please review

### CODE REVIEW

**Comment by eriviere** [comment]
Is it supposed to fix the issue "callback is not a function" on both Linux and Windows?
If yes, please accept this pull request asap :+1:

**Comment by winfinit** [comment]
Project was moved, please resubmit this pull request in mockgoose/mockgoose

**Comment by sibelius** [comment]
this is fixed already here: https://github.com/Mockgoose/Mockgoose

**Comment by winfinit** [comment]
6.0.8 was just published

**Comment by winfinit** [comment]
if you are still interested to contribute and problem persists in new codebase, please submit your pull request under mockgoose/mockgoose

**Pull request closed without merging**
